### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by Vlix** [Vlix/http-types#21]
New `bytestring >= 0.11.1.0` constraint on `doctests` fails on older stack resolvers.

Need to add the constaint to the custom `stack.yaml`s.

**Comment by Vlix** [comment]
@felixonmars 
Uhmmm, I just noticed I added a setup for the doctests back in 2023 that should kick in when there's no `Show Builder` instance.
Why did it give you an error?

**Comment by felixonmars** [comment]
Oops, my bad. I only tested the released versions and didn't notice the fix in master. My PR should be reverted I think...

**Comment by Vlix** [comment]
Reverted with #22 :+1:
